### PR TITLE
add passkeys.guru

### PR DESCRIPTION
**Pull request by meirwah**
add passkeys.guru for passkeys demos

### CODE REVIEW

**Comment by timcappalli** [comment]
Hi - thanks for the PR. This demo site does not currently follow best practices for passkeys. If you're willing to make the changes below, we can include the site.

- The button should use the industry passkey icon (https://fidoalliance.org/overview/legal/fido-trademark-and-service-mark-usage-agreement-for-websites/, https://media.fidoalliance.org/wp-content/uploads/2022/09/Passkey-Style-Guide.zip)
- The button should say "Continue with a passkey" ("passkey" by itself isn't a thing, it is "a passkey" or "passkeys" and lowercase p)
- Require discoverable credentials (`residentKey: "required"`, `"requireResidentKey": true`)

**Comment by meirwah** [comment]
10x for the feedback @timcappalli !!

fixed the button text:
image

will fix the other 2 points, and update here

**Comment by meirwah** [comment]
@timcappalli fixed the other 2 issues, let me know if anything else is missing:
image

**Comment by timcappalli** [comment]
@meirwah I just did some testing and it looks like you might still be setting `cross-platform` attachment (which results in external authenticators being preferred).

Please remove the attachment option from your creation call.

**Comment by meirwah** [comment]
will fix that

**Comment by meirwah** [comment]
@timcappalli I checked , and it seems we don't send that option

Might it be you used an existing user email to signin/up ? that you have created in the past ?

Can you try with a new user, do you see external authenticators being preferred still ?

**Comment by timcappalli** [comment]
I've just been throwing random values in. I just tried again and it appears to be correct now.

**Review by timcappalli — APPROVED** [review]

**Pull request merged**
