### PR TITLE
Replace YouTube embed with static image

### LINKED ISSUE #70: Remove YouTube embed on homepage
The embedded YouTube video is very chatty cross-origin, even with the no cookie embed version. Replace with a static image that links off to YouTube.

### PR DESCRIPTION
**Pull request by MasterKale**
This PR replaces the YouTube embed with a static screenshot and a link to the video. Clicking the link will open the video in a new tab.

Fixes #70.

## Preview

**Desktop:**

Screenshot 2022-10-27 at 9 27 04 AM

**Mobile:**

Screenshot 2022-10-27 at 9 27 20 AM

## Privacy enhancements

The YouTube embed was incredibly opportunistic in the number of additional files it downloaded, and it's anyone's guess if the files were legitimately required for the video to play vs attempts to identify the user via fingerprinting.

Remove the embed removed many extraneous third-party downloads (except for CloudFlare analytics):

**Network calls before:**

Screenshot 2022-10-27 at 9 23 53 AM

**Network calls after:**

Screenshot 2022-10-27 at 9 24 11 AM

### CODE REVIEW

**Comment by dontcallmedom** [comment]
In case this helps, you could instead use the CloudFlare Stream hosted version we put together for TPAC (with FIDO's permissions); it has the additional bonus of having captions: https://www.w3.org/2022/09/TPAC/demos/passkeys.html
```
<iframe id=video width=640 height=360
            title="WebAuthn & Passkeys"
            src="[https://customer-0kix77mxh2zzzae0.cloudflarestream.com/24b75b7235603692ffbcc66597c26077/iframe?defaultTextTrack=en&amp;poster=https%3A%2F%2Fcustomer-0kix77mxh2zzzae0.cloudflarestream.com%2F24b75b7235603692ffbcc66597c26077%2Fthumbnails%2Fthumbnail.jpg%3Ftime%3D7s%26height%3D360](view-source:https://customer-0kix77mxh2zzzae0.cloudflarestream.com/24b75b7235603692ffbcc66597c26077/iframe?defaultTextTrack=en&poster=https%3A%2F%2Fcustomer-0kix77mxh2zzzae0.cloudflarestream.com%2F24b75b7235603692ffbcc66597c26077%2Fthumbnails%2Fthumbnail.jpg%3Ftime%3D7s%26height%3D360)"
            frameborder=0 allow="accelerometer; autoplay; encrypted-media;
            picture-in-picture" allowFullScreen></iframe>
```

I *think* it should work from any origin, but if it doesn't, I'm also happy to look into what it would take to make it work (although I won't be able to do so before Nov 7)

**Comment by timcappalli** [comment]
@MasterKale can you put the image in the images folder under static?

**Comment by MasterKale** [comment]
Done and done

**Review by timcappalli — APPROVED** [review]
lgtm

**Pull request merged**
