### PR TITLE
Change license to CC BY-NC-ND 4.0

### PR DESCRIPTION
**Pull request by timcappalli**
Changes the license from Creative Commons `Attribution-ShareAlike license (CC-BY-SA)` to [`Attribution-NonCommercial-NoDerivatives 4.0 International`](https://creativecommons.org/licenses/by-nc-nd/4.0/) with some additional terms.

Also removes Twitter links and tweaks the "Brought to you by" text.

### CODE REVIEW

**Review by MasterKale — APPROVED** [review]
I'm fine with this, I just want to double-check whether this license still makes it okay to **quote** portions of passkeys.dev content, unmodified, on other sites.

**Comment by MasterKale** [comment]
From a respected member of the W3C community:

> Quoting will usually be defensible fair use, whatever the license

That answers my question, I'm 100% fine with this.

**Comment by abergs** [comment]
I'm good with this.

> NonCommercial — You may not use the material for [commercial purposes ](https://creativecommons.org/licenses/by-nc-nd/4.0/#ref-commercial-purposes).

It did occur to me that we may want to clarify the non-commercial part of the license. We still want to allow businesses to link to passkeys.dev in their docs etc, so spelling that out might remove any gray area etc?

**Comment by timcappalli** [comment]
Linking is always allowed, regardless of license, as it's a public web resource.

**Pull request merged**
